// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nhkukndmzfgyfctehwye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oa3VrbmRtemZneWZjdGVod3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTYzNzQsImV4cCI6MjA3MjE5MjM3NH0.nfDYfq3jNAm9O1JxreMW1TZqPWUZsZEnrb71FsiltCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);